### ISSUE TITLE
Add sorting and filtering

### ISSUE THREAD

**Issue by chris-technicate** [netniV/racktables-tasks#2]
Please add sorting and filtering to the following pages:

Tasks Outstanding
Task History
Task Definitions

**Comment by chris-technicate** [comment]
on my deployment can you visit this page:
/index.php?page=reports&tab=customBilling

click search
It would be killer to have this type of filtering and sorting on all 3 pages

We wrote this code on an internal plugin based loosely off this plugin:
https://github.com/RackTables/racktables-contribs/tree/master/extensions/plugins

**Comment by chris-technicate** [comment]
Filtering does not at all work. use mine, type filters in to the definition field, the list sorts differently but everything is still there.

**Comment by netniV** [comment]
The implementation is using the same PICnet filter script.  I suspect that it may require something i'm not providing in the same fashion as your other plugin/report.

**Comment by netniV** [comment]
This should now be resolved
