### ISSUE TITLE
Task History should not show open tasks

### ISSUE THREAD

**Issue by chris-technicate** [netniV/racktables-tasks#3]
Task history should not show outstanding tasks as this is only the history of

**Comment by netniV** [comment]
This should now be rectified.

**Comment by chris-technicate** [comment]
Confirmed working

**Comment by netniV** [comment]
You may wish to update again.  Just pushed another change related to this.

**Comment by chris-technicate** [comment]
Like I said "Confirmed Working"
Meaning -- good to go!

**Comment by netniV** [comment]
I appreciate it was. But I made some more changes as I found issues.  However, if it's still good that's good 👍
